---

- name: epg configuration
  cisco.aci.aci_epg:
    host: "{{ ansible_host }}"
    username: "{{ ansible_user }}"
    password: "{{ ansible_ssh_pass }}"
    tenant: "{{ aci_epg.tenant }}"
    ap: "{{ aci_epg.ap }}"
    epg: "{{ aci_epg.epg | default(inventory_hostname)  }}"
    description: "{{ aci_epg.description | default(omit) }}"
    bd: "{{ aci_epg.bd }}"
    state: "{{ aci_epg_state }}"
  tags: [always]